spring:
  application:
    name: CoreShortener
  profiles:
    active: dev

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B59703D}
      access-token-expiration-ms: 900000     # 15 minutes
      refresh-token-expiration-ms: 604800000 # 7 days

---
spring:
  config:
    activate:
      on-profile: dev

  security:
    user:
      name: admin
      password: admin123

  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
